Data Airbnb :

https://insideairbnb.com/fr/get-the-data/

# 1. Importation, chargement des tables et visualisation des DataFrames
#& Nettoyage de données (suppression des doublons, des anomalies, mise à jour des types de données)

In [60]:
#importer pandas

import pandas as pd



*   Table : listing_paris

In [61]:
#charger la table : listing_paris : Détail de chaque annonce (prix, type, localisation…)
!wget https://data.insideairbnb.com/italy/puglia/puglia/2025-09-29/visualisations/listings.csv
df_listing_paris = pd.read_csv("/content/listings.csv")
df_listing_paris.head()

#Italie > Paris

--2026-04-23 21:04:43--  https://data.insideairbnb.com/italy/puglia/puglia/2025-09-29/visualisations/listings.csv
Resolving data.insideairbnb.com (data.insideairbnb.com)... 18.239.105.106, 18.239.105.49, 18.239.105.20, ...
Connecting to data.insideairbnb.com (data.insideairbnb.com)|18.239.105.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8073986 (7.7M) [application/csv]
Saving to: ‘listings.csv.2’

listings.csv.2      100%[===================>]   7.70M  --.-KB/s    in 0.05s

2026-04-23 21:04:44 (169 MB/s) - ‘listings.csv.2’ saved [8073986/8073986]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,37125,pietraviva una dimora nella natura,160280,Francesca,Bari,Conversano,41.00059,17.15027,Entire home/apt,100.0,5,1,2011-05-27,0.01,1,365,0,IT072019C200095430
1,45663,Luxury 10 Bedroom Villa with Pool,202935,Steven,Bari,Terlizzi,41.10029,16.55411,Private room,1245.0,1,3,2019-08-16,0.02,1,337,0,IT072043B500086352
2,60925,I SETTE CONI - TRULLO LAVANDA,294274,Anna,Brindisi,Ostuni,40.71846,17.43095,Entire home/apt,262.0,7,109,2025-09-28,0.69,3,94,9,IT074012B400027441
3,61987,Gargano Casa Vacanze con servizio colazione,301235,Giuseppe,Foggia,Vico del Gargano,41.90212,15.96531,Entire home/apt,40.0,2,53,2024-08-05,0.31,7,361,0,IT071059B400023458
4,61989,Pizzicato BeB Gargano Monolocale Nocciola,301235,Giuseppe,Foggia,Vico del Gargano,41.90139,15.96530,Entire home/apt,50.0,2,15,2023-05-21,0.17,7,365,0,NaN

In [62]:
#vérifier types de colonnes et non-null
df_listing_paris.info()
df_listing_paris.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48553 entries, 0 to 48552
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48553 non-null  int64
 1   name                            48553 non-null  object
 2   host_id                         48553 non-null  int64
 3   host_name                       48515 non-null  object
 4   neighbourhood_group             48553 non-null  object
 5   neighbourhood                   48553 non-null  object
 6   latitude                        48553 non-null  float64
 7   longitude                       48553 non-null  float64
 8   room_type                       48553 non-null  object
 9   price                           42923 non-null  float64
 10  minimum_nights                  48553 non-null  int64
 11  number_of_reviews               48553 non-null  int64
 12  last_review                     33297 non-null  object
 13  reviews_per_month               33297 non-null  float64
 14  calculated_host_listings_count  48553 non-null  int64
 15  availability_365                48553 non-null  int64
 16  number_of_reviews_ltm           48553 non-null  int64
 17  license                         42964 non-null  object
dtypes: float64(4), int64(7), object(7)
memory usage: 6.7+ MB

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,4.855300e+04,4.855300e+04,48553.000000,48553.000000,42923.000000,48553.000000,48553.000000,33297.00000,48553.000000,48553.000000,48553.000000
mean,7.360601e+17,2.822209e+08,40.556929,17.573681,360.365771,6.478096,12.709781,0.63038,63.093794,210.801228,3.174284
std,5.745776e+17,2.306030e+08,0.512880,0.691154,1455.954868,12.664218,30.933893,0.85700,235.520406,138.858648,7.193672
min,3.712500e+04,1.690100e+04,39.792330,15.005120,2.000000,1.000000,0.000000,0.01000,1.000000,0.000000,0.000000
25%,4.319454e+07,5.383051e+07,40.135630,17.220500,65.000000,1.000000,0.000000,0.12000,1.000000,78.000000,0.000000
50%,8.951884e+17,2.343517e+08,40.461930,17.662336,90.000000,2.000000,2.000000,0.33000,3.000000,242.000000,0.000000
75%,1.232538e+18,4.991854e+08,40.910229,18.133240,144.000000,5.000000,11.000000,0.79000,11.000000,358.000000,3.000000
max,1.520310e+18,7.211089e+08,42.121790,18.506376,52500.000000,999.000000,716.000000,13.00000,1393.000000,365.000000,147.000000

In [63]:
#vérifier le nombre de doublons
df_listing_paris.duplicated().sum()

np.int64(0)

In [64]:
#focus non-null
df_listing_paris.isnull().sum()

id                                    0
name                                  0
host_id                               0
host_name                            38
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                              5630
minimum_nights                        0
number_of_reviews                     0
last_review                       15256
reviews_per_month                 15256
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
license                            5589
dtype: int64

In [65]:
#remplacer Null colonne host_name par "Unknown"
df_listing_paris['host_name'] = df_listing_paris['host_name'].fillna("Unknown")

In [66]:
#gérer les Null colonne Price
##supprimer les lignes
##df_listing_paris = df_listing_paris.dropna(subset=['price'])
## ou remplacer par médiane
##df_listing_paris['price'] = df_listing_paris['price'].fillna(df_listing_paris['price'].median())

In [67]:
#Gestion des Null colonne License
df_listing_paris['license'] = df_listing_paris['license'].fillna("No license")

In [68]:
#Gestion des Null colonnes reviews_per_month & last_review
df_listing_paris['reviews_per_month'] = df_listing_paris['reviews_per_month'].fillna(0)
df_listing_paris['last_review'] = df_listing_paris['last_review'].fillna("No review")

In [69]:
#vérification data
df_listing_paris.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            0
neighbourhood_group                  0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                             5630
minimum_nights                       0
number_of_reviews                    0
last_review                          0
reviews_per_month                    0
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                              0
dtype: int64



*   Table : reviews_paris

In [70]:
#charger la table : reviews_paris : Avis des voyageurs
!wget https://data.insideairbnb.com/italy/puglia/puglia/2025-09-29/visualisations/reviews.csv
df_reviews_paris = pd.read_csv("/content/reviews.csv")
df_reviews_paris.head()

--2026-04-23 21:04:44--  https://data.insideairbnb.com/italy/puglia/puglia/2025-09-29/visualisations/reviews.csv
Resolving data.insideairbnb.com (data.insideairbnb.com)... 18.239.105.106, 18.239.105.49, 18.239.105.20, ...
Connecting to data.insideairbnb.com (data.insideairbnb.com)|18.239.105.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14276429 (14M) [application/csv]
Saving to: ‘reviews.csv.2’

reviews.csv.2       100%[===================>]  13.61M  --.-KB/s    in 0.06s

2026-04-23 21:04:44 (211 MB/s) - ‘reviews.csv.2’ saved [14276429/14276429]

   listing_id        date
0       37125  2011-05-27
1       45663  2012-08-22
2       45663  2017-04-27
3       45663  2019-08-16
4       60925  2012-10-02

In [71]:
#vérifier types de colonnes et non-null
df_reviews_paris.info()
df_reviews_paris.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 617098 entries, 0 to 617097
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   listing_id  617098 non-null  int64
 1   date        617098 non-null  object
dtypes: int64(1), object(1)
memory usage: 9.4+ MB

         listing_id
count  6.170980e+05
mean   2.985634e+17
std    4.589847e+17
min    3.712500e+04
25%    1.720759e+07
50%    3.607224e+07
75%    6.737946e+17
max    1.515338e+18

In [72]:
#changement date object > DateTime
df_reviews_paris['date'] = pd.to_datetime(df_reviews_paris['date'])

In [73]:
#vérification
df_reviews_paris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 617098 entries, 0 to 617097
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   listing_id  617098 non-null  int64
 1   date        617098 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 9.4 MB

In [74]:
#vérifier le nombre de doublons
df_reviews_paris.duplicated().sum()

np.int64(317)

In [75]:
#visualiser les lignes en doublon
df_reviews_paris[df_reviews_paris.duplicated(keep=False)]

                 listing_id       date
1003                 342074 2016-03-31
1004                 342074 2016-03-31
2403                 395480 2016-08-25
2404                 395480 2016-08-25
7276                 743621 2021-07-05
...                     ...        ...
602878  1363645743509220559 2025-06-09
602884  1363645743509220559 2025-07-28
602885  1363645743509220559 2025-07-28
612789  1437700639781322278 2025-07-13
612790  1437700639781322278 2025-07-13

[619 rows x 2 columns]

In [76]:
#supprimer les doublons
df_reviews_paris= df_reviews_paris.drop_duplicates()

In [77]:
#vérification post suppression doublons
df_reviews_paris.duplicated().sum()

np.int64(0)

* Table : neighbourhoods_paris

In [78]:
#charger la table : neighbourhoods_paris : Contours géographiques des quartiers
!wget https://data.insideairbnb.com/italy/puglia/puglia/2025-09-29/visualisations/neighbourhoods.csv
df_neighbourhoods_paris = pd.read_csv("/content/neighbourhoods.csv")
df_neighbourhoods_paris.head()

--2026-04-23 21:04:45--  https://data.insideairbnb.com/italy/puglia/puglia/2025-09-29/visualisations/neighbourhoods.csv
Resolving data.insideairbnb.com (data.insideairbnb.com)... 18.239.105.106, 18.239.105.49, 18.239.105.20, ...
Connecting to data.insideairbnb.com (data.insideairbnb.com)|18.239.105.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4992 (4.9K) [application/csv]
Saving to: ‘neighbourhoods.csv.2’

neighbourhoods.csv. 100%[===================>]   4.88K  --.-KB/s    in 0s

2026-04-23 21:04:45 (874 MB/s) - ‘neighbourhoods.csv.2’ saved [4992/4992]

  neighbourhood_group          neighbourhood
0                Bari  Acquaviva delle Fonti
1                Bari                Adelfia
2                Bari            Alberobello
3                Bari               Altamura
4                Bari                   Bari

In [79]:
#vérifier types de colonnes et non-null
df_neighbourhoods_paris.info()
df_neighbourhoods_paris.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   neighbourhood_group  258 non-null    object
 1   neighbourhood        258 non-null    object
dtypes: object(2)
memory usage: 4.2+ KB

       neighbourhood_group neighbourhood
count                  258           258
unique                   6           258
top                  Lecce    Torricella
freq                    97             1

In [80]:
#vérifier le nombre de doublons
df_neighbourhoods_paris.duplicated().sum()

np.int64(0)



*   Table : calendar_paris

In [81]:
#charger la table : calendar_paris : Disponibilités et prix par date
!wget https://data.insideairbnb.com/italy/puglia/puglia/2025-09-29/data/calendar.csv.gz
df_calendar_paris = pd.read_csv("/content/calendar.csv.gz")
df_calendar_paris.head()

--2026-04-23 21:04:45--  https://data.insideairbnb.com/italy/puglia/puglia/2025-09-29/data/calendar.csv.gz
Resolving data.insideairbnb.com (data.insideairbnb.com)... 18.239.105.106, 18.239.105.49, 18.239.105.20, ...
Connecting to data.insideairbnb.com (data.insideairbnb.com)|18.239.105.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42712017 (41M) [application/x-gzip]
Saving to: ‘calendar.csv.gz.2’

calendar.csv.gz.2   100%[===================>]  40.73M   125MB/s    in 0.3s

2026-04-23 21:04:46 (125 MB/s) - ‘calendar.csv.gz.2’ saved [42712017/42712017]

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,440091,2025-09-30,f,NaN,NaN,6,36
1,440091,2025-10-01,f,NaN,NaN,6,36
2,440091,2025-10-02,f,NaN,NaN,6,36
3,440091,2025-10-03,t,NaN,NaN,6,36
4,440091,2025-10-04,t,NaN,NaN,6,36

In [82]:
#vérifier types de colonnes et non-null
df_calendar_paris.info()
df_calendar_paris.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17721850 entries, 0 to 17721849
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            object
 2   available       object
 3   price           float64
 4   adjusted_price  float64
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: float64(2), int64(3), object(2)
memory usage: 946.4+ MB

         listing_id  price  adjusted_price  minimum_nights  maximum_nights
count  1.772185e+07    0.0             0.0    1.772185e+07    1.772185e+07
mean   7.360601e+17    NaN             NaN    6.543765e+00    4.914507e+02
std    5.745717e+17    NaN             NaN    1.237137e+01    6.407012e+02
min    3.712500e+04    NaN             NaN    1.000000e+00    1.000000e+00
25%    4.319454e+07    NaN             NaN    1.000000e+00    3.000000e+01
50%    8.951884e+17    NaN             NaN    2.000000e+00    3.650000e+02
75%    1.232538e+18    NaN             NaN    5.000000e+00    1.125000e+03
max    1.520310e+18    NaN             NaN    7.190000e+02    9.999900e+04

In [83]:
#changement date object > DateTime
df_calendar_paris['date'] = pd.to_datetime(df_reviews_paris['date'])

In [84]:
#vérification
df_calendar_paris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17721850 entries, 0 to 17721849
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            datetime64[ns]
 2   available       object
 3   price           float64
 4   adjusted_price  float64
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 946.4+ MB

In [85]:
#vérifier le nombre de doublons
df_calendar_paris.duplicated().sum()

np.int64(16978952)

In [86]:
#visualiser les doublons
df_calendar_paris[df_calendar_paris.duplicated(keep=False)]

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
12,440091,2013-06-23,t,NaN,NaN,6,36
121,440091,2013-06-23,t,NaN,NaN,6,36
137,37125,2017-06-06,t,NaN,NaN,5,730
138,37125,2017-07-02,t,NaN,NaN,5,730
139,37125,2017-10-26,t,NaN,NaN,5,730
...,...,...,...,...,...,...,...
17721845,1520310454098459242,NaT,t,NaN,NaN,1,1125
17721846,1520310454098459242,NaT,t,NaN,NaN,1,1125
17721847,1520310454098459242,NaT,t,NaN,NaN,1,1125
17721848,1520310454098459242,NaT,t,NaN,NaN,1,1125
17721849,1520310454098459242,NaT,t,NaN,NaN,1,1125

In [87]:
#supprimer les doublons
df_calendar_paris= df_calendar_paris.drop_duplicates()

In [88]:
#vérification post suppression doublons
df_calendar_paris.duplicated().sum()

np.int64(0)

In [89]:
#visualiser le nombre de Null
df_calendar_paris.isnull().sum()

listing_id             0
date              203951
available              0
price             742898
adjusted_price    742898
minimum_nights         0
maximum_nights         0
dtype: int64

In [90]:
#gérer les Null colonne Price
##supprimer les lignes
##df_calendar_paris = df_calendar_paris.dropna(subset=['price'])
## ou remplacer par médiane
##df_calendar_paris['price'] = df_calendar_paris['price'].fillna(df_calendar_paris['price'].median())

# 2. Détermination de clés primaires

Colonne en commun : listing_id

clé primaire : table listing, colonne "id"

clés étrangères : autres tables, colonne "listing_id"

# 3. Création de jointures