In [ ]:
#charger les tables

import pandas as pd

df_listings = pd.read_csv("listings_paris.csv")
df_reviews = pd.read_csv("reviews.csv")
df_neighbourhoods = pd.read_csv("neighbourhoods_paris.csv")

In [2]:
import pandas as pd

In [1]:
!wget https://data.insideairbnb.com/france/ile-de-france/paris/2025-09-12/data/calendar.csv.gz

--2026-04-13 09:25:30--  https://data.insideairbnb.com/france/ile-de-france/paris/2025-09-12/data/calendar.csv.gz
Resolving data.insideairbnb.com (data.insideairbnb.com)... 143.204.204.62, 143.204.204.129, 143.204.204.13, ...
Connecting to data.insideairbnb.com (data.insideairbnb.com)|143.204.204.62|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72087684 (69M) [application/x-gzip]
Saving to: ‘calendar.csv.gz’

calendar.csv.gz     100%[===================>]  68.75M  35.4MB/s    in 1.9s

2026-04-13 09:25:32 (35.4 MB/s) - ‘calendar.csv.gz’ saved [72087684/72087684]

In [4]:
df_calendar = pd.read_csv("/content/calendar.csv.gz")
#EOFError: Compressed file ended before the end-of-stream marker was reached

In [5]:
df_calendar.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2719440,2025-09-12,f,NaN,NaN,2,7
1,2719440,2025-09-13,f,NaN,NaN,2,7
2,2719440,2025-09-14,f,NaN,NaN,2,7
3,2719440,2025-09-15,f,NaN,NaN,2,7
4,2719440,2025-09-16,f,NaN,NaN,2,7

In [ ]:
#Visualiser Listings > Détail de chaque annonce (prix, type, localisation…)
df_listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2719440,https://www.airbnb.com/rooms/2719440,20250912034503,2025-09-12,previous scrape,Nice flat close to Montparnasse,This beautiful apartment is very well located ...,"The neighborhood is very nice, feel free to sh...",https://a0.muscache.com/pictures/295786e7-116c...,13915159,...,4.94,4.86,4.73,7510702406383,f,1,1,0,0,0.57
1,2721397,https://www.airbnb.com/rooms/2721397,20250912034503,2025-09-12,previous scrape,"Marais - Charming loft, river view","In the heart of historical Paris le Marais, gr...",Le Marais is the heart of Paris. Few years ago...,https://a0.muscache.com/pictures/de55313f-9b4b...,13925876,...,4.95,4.91,4.85,7510400455677,f,1,1,0,0,0.66
2,2726092,https://www.airbnb.com/rooms/2726092,20250912034503,2025-09-12,previous scrape,Superbe 2 pièces idéalement placé,A stone's throw from Parc Monceau and the Arc ...,Quiet and residential area... Close to the Bat...,https://a0.muscache.com/pictures/6d6c4bc6-9473...,13612373,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
3,2726327,https://www.airbnb.com/rooms/2726327,20250912034503,2025-09-12,previous scrape,"Cozy place, Sacré Coeur Montmartre in the SoPi",Cozy apartment close to everything.<br />Perfe...,One of the most trendy corners of the capital ...,https://a0.muscache.com/pictures/6b569382-aed7...,7483725,...,4.97,4.92,4.67,7510901014972,f,1,1,0,0,0.72
4,2727929,https://www.airbnb.com/rooms/2727929,20250912034503,2025-09-12,previous scrape,Appartement d'architecte - Montmartre,"Our apartment, refurbished by an architect in ...",The apartment is in the heart of Paris's 18th ...,https://a0.muscache.com/pictures/miso/Hosting-...,13960346,...,5.00,4.57,5.00,7511808333770,f,1,1,0,0,0.25

In [ ]:
#df_calendar.head()
#Disponibilités et prix par date

FileNotFoundError: [Errno 2] No such file or directory: 'calendar_paris.csv.gz'

In [ ]:
#Visualiser reviews : Avis des voyageurs
df_reviews.head()

   listing_id        date
0        3109  2017-10-28
1        3109  2017-11-03
2        3109  2018-07-24
3        3109  2019-10-24
4        3109  2025-04-08

In [ ]:
#Visualiser neighbourhood : Contours géographiques des quartiers
df_neighbourhoods.head()

   neighbourhood_group        neighbourhood
0                  NaN  Batignolles-Monceau
1                  NaN               Bourse
2                  NaN      Buttes-Chaumont
3                  NaN    Buttes-Montmartre
4                  NaN               Élysée

In [ ]:
#df.info()
#df.describe()
#df.isnull().sum()